# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Install Skopeo  # 新增安装步骤
      run: sudo apt-get update && sudo apt-get install -y skopeo

    - name: Login to Aliyun Registry  # 修正步骤名称
      uses: docker/login-action@v2
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUN_USERNAME }}  # 使用Secrets
        password: ${{ secrets.ALIYUN_PASSWORD }}
        logout: false
        
    - name: Sync Image to Aliyun Registry  # 修正步骤名称
      run: |
        skopeo copy --dest-creds "${{ secrets.ALIYUN_USERNAME }}:${{ secrets.ALIYUN_PASSWORD }}" \
          docker://docker.io/starrocks/be-ubuntu:3.3-latest \
          docker://registry.cn-hangzhou.aliyuncs.com/docker_image-ljx/starrocks_be-ubuntu:3.3-latest